#---------------------------------------------------------------------------
# Get and build itk

set(ITK_TAG "v5.4.3")
set(SPH_ITK_CMAKE_ARGS
  ${SPH_EXTERNAL_CMAKE_ARGS}
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DITK_USE_SYSTEM_EIGEN:BOOL=ON
  -DEigen3_DIR:PATH=${Eigen3_DIR}
  -DBUILD_TESTING:BOOL=OFF
  -DBUILD_EXAMPLES:BOOL=OFF
  -DITK_LEGACY_REMOVE:BOOL=ON
  -DITKV3_COMPATIBILITY:BOOL=OFF
  -DITK_BUILD_DEFAULT_MODULES:BOOL=OFF
  -DModule_ITKCommon:BOOL=ON
  -DModule_ITKIOImageBase:BOOL=ON
  -DModule_ITKIONIFTI:BOOL=ON
  -DModule_ITKIONRRD:BOOL=ON
  -DModule_MGHIO:BOOL=OFF
  -DModule_ITKIOMINC:BOOL=OFF
  -DModule_ITKIOXML:BOOL=ON
  -DModule_ITKIOGDCM:BOOL=OFF
  -DModule_ITKGDCM:BOOL=OFF
  -DBUILD_SHARED_LIBS:BOOL=OFF
  -DITK_INSTALL_NO_DEVELOPMENT:BOOL=ON
  -DITK_WRAPPING:BOOL=OFF
  -DITK_USE_FFTWD:BOOL=OFF
  -DITK_USE_FFTWF:BOOL=OFF
)
if(MINGW)
  list(APPEND SPH_ITK_CMAKE_ARGS
    -DGDCM_USE_SYSTEM_POSIX_ALLOC:BOOL=OFF
  )
endif()

ExternalProject_Add(ITK
  DEPENDS Eigen3
  GIT_REPOSITORY "https://github.com/InsightSoftwareConsortium/ITK"
  GIT_TAG "${ITK_TAG}"
  UPDATE_DISCONNECTED ON
  SOURCE_DIR ITK
  BINARY_DIR ITK-build
  CMAKE_GENERATOR ${gen}
  LOG_DOWNLOAD ON
  LOG_OUTPUT_ON_FAILURE ON
  PATCH_COMMAND ${CMAKE_COMMAND}
    -DITK_SOURCE_DIR=<SOURCE_DIR>
    -P ${CMAKE_SOURCE_DIR}/cmake/PatchITK.cmake
  CMAKE_ARGS
    ${SPH_ITK_CMAKE_ARGS}
  INSTALL_COMMAND ""
)

set(ITK_DIR ${CMAKE_BINARY_DIR}/ITK-build)
